---
- hosts: all
  become: yes
  tasks:
  - name: Install apache server
    yum:
      name: httpd
      state: present
  - name: Ensure Apache service is running
    service:
      name: httpd
      state: started
      enabled: yes    