---
- hosts: all
  become: yes
  tasks: 
  - name: Install openjdk 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: just checking group varibales
    debug:
      msg: "{{log_folder}}"
  - name: just checking hosts vars
    debug:
      msg: "{{check_command}}"
  - name: Install Tomcat
    get_url:
      url: http://mirror.reverse.net/pub/apache/tomcat/tomcat-9/v9.0.29/bin/apache-tomcat-9.0.29.tar.gz
      dest: /usr/share 
  - name: download install jenkins to webapps/
    get_url:
      url: http://updates.jenkins-ci.org/download/war/2.208/jenkins.war
      dest: /usr/share
  - name: Run Tomcat
    systemd:
      name: tomcat       
      state: restarted
      enabled: yes
      daemon_reload: yes
  - name: Run Jenkins
    systemd: 
      name: jenkins
      state: started
      enabled: yes    
