---
- hosts: appserver
  become: yes
  tasks: 
  - name: Install openjdk 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: Install tomcat 8
    yum:
      name: tomcat 
      version: 7.0.23.0
      state: latest
  - name: download install jenkins to webapps/
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.190.3/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes